# Pydantic request/response schemas
# models/schemas.py
# FastAPI-level Pydantic schemas — request validation and response serialization.
# These are the public contract between the React frontend and the FastAPI backend.
# Nothing inside agents/ should ever import from this file.

from pydantic import BaseModel, Field, field_validator
from typing import Optional, Literal
from datetime import date


# ---------------------------------------------------------------------------
# Shared / base
# ---------------------------------------------------------------------------

class BaseResponse(BaseModel):
    """
    Common envelope wrapping every API response.
    Gives the frontend a consistent shape to check before reading payload.
    """
    success: bool
    message: str                          # human-readable status e.g. "OK" or error detail


# ---------------------------------------------------------------------------
# /chat
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    session_id: str = Field(
        ...,
        min_length=8,
        max_length=64,
        description="UUID identifying the user's conversation session.",
        examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"],
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="The user's natural language query.",
        examples=["What is the PNR status of 1234567890?"],
    )

    @field_validator("message")
    @classmethod
    def message_not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("message must not be blank or whitespace only.")
        return v.strip()


class ChatResponse(BaseResponse):
    session_id: str
    intent: Optional[str] = Field(
        default=None,
        description="The intent the supervisor classified this query as.",
    )
    response: str = Field(
        ...,
        description="Natural language answer generated by the responsible agent.",
    )


# ---------------------------------------------------------------------------
# /train-status
# ---------------------------------------------------------------------------

class TrainStatusRequest(BaseModel):
    train_number: str = Field(
        ...,
        min_length=4,
        max_length=6,
        pattern=r"^\d{4,6}$",
        description="Indian Railways train number (4-6 digits).",
        examples=["12951", "22222"],
    )
    journey_date: Optional[str] = Field(
        default=None,
        description="Optional journey date in YYYY-MM-DD format. Defaults to today in IST.",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session ID to associate with conversation memory.",
    )


class NextStationDetails(BaseModel):
    stationCode: str
    expectedArrival: Optional[str] = None
    expectedDeparture: Optional[str] = None
    distanceToNextStationKm: Optional[float] = None
    delayArrivalMinutes: Optional[int] = None


class CurrentLocation(BaseModel):
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    stationCode: Optional[str] = None
    status: Optional[str] = None
    distanceFromOriginKm: Optional[float] = None
    nextStation: Optional[NextStationDetails] = None


class RouteStop(BaseModel):
    sequence: int
    stationCode: str
    scheduledArrival: Optional[str] = None
    scheduledDeparture: Optional[str] = None
    actualArrival: Optional[str] = None
    actualDeparture: Optional[str] = None
    delayArrivalMinutes: Optional[int] = None
    delayDepartureMinutes: Optional[int] = None
    expectedDelayArrivalMinutes: Optional[int] = None
    expectedDelayDepartureMinutes: Optional[int] = None
    platform: Optional[str] = None


class TrainStatusResponse(BaseResponse):
    trainNumber: str
    trainName: str = "Unknown"
    journeyDate: Optional[str] = None
    lastUpdatedAt: Optional[str] = None
    currentLocation: Optional[CurrentLocation] = None
    route: list[RouteStop] = Field(default_factory=list)
    natural_language_summary: str = Field(
        ...,
        description="Agent-generated human-readable summary of the train's current status.",
        examples=["Rajdhani Express is currently at Varanasi and running 15 minutes late."],
    )


# ---------------------------------------------------------------------------
# /search-trains
# ---------------------------------------------------------------------------

class SearchTrainsRequest(BaseModel):
    source: str = Field(
        ...,
        min_length=2,
        max_length=5,
        pattern=r"^[A-Z]{2,5}$",
        description="Source station code in uppercase.",
        examples=["ST", "NDLS"],
    )
    destination: str = Field(
        ...,
        min_length=2,
        max_length=5,
        pattern=r"^[A-Z]{2,5}$",
        description="Destination station code in uppercase.",
        examples=["BCT", "HWH"],
    )
    session_id: Optional[str] = None

    @field_validator("destination")
    @classmethod
    def source_destination_different(cls, v: str, info) -> str:
        source = info.data.get("source")
        if source and v == source:
            raise ValueError("source and destination cannot be the same station.")
        return v


class TrainSummary(BaseModel):
    """
    Represents one train in the search results list.
    Nested inside SearchTrainsResponse.
    """
    train_number: str
    train_name: Optional[str] = "Unknown"
    departure_time: str = Field(..., examples=["06:20"])
    arrival_time: str = Field(..., examples=["13:45"])
    duration: str = Field(..., examples=["7h 25m"])
    days_of_operation: list[str] = Field(
        ...,
        description="Days this train runs. E.g. ['Mon', 'Wed', 'Fri']",
    )
    available_classes: list[str] = Field(
        ...,
        description="Classes available on this train.",
        examples=[["SL", "3A", "2A", "1A"]],
    )
    distance_km: Optional[float] = None


class SearchTrainsResponse(BaseResponse):
    source: str
    destination: str
    journey_date: Optional[str] = None
    total_trains_found: int = Field(..., ge=0)
    trains: list[TrainSummary]
    natural_language_summary: str = Field(
        ...,
        description="Agent-generated summary of available trains.",
        examples=["Found 6 trains from Surat to Mumbai on 15 Jan. Earliest is 06:20 Shatabdi."],
    )


# ---------------------------------------------------------------------------
# /availability
# ---------------------------------------------------------------------------

class AvailabilityRequest(BaseModel):
    train_number: str = Field(
        ...,
        min_length=4,
        max_length=6,
        pattern=r"^\d{4,6}$",
        examples=["12951"],
    )
    source: str = Field(
        ...,
        min_length=2,
        max_length=5,
        pattern=r"^[A-Z]{2,5}$",
        examples=["ST"],
    )
    destination: str = Field(
        ...,
        min_length=2,
        max_length=5,
        pattern=r"^[A-Z]{2,5}$",
        examples=["BCT"],
    )
    journey_date: date = Field(..., examples=["2025-01-15"])
    class_type: Literal["SL", "3A", "2A", "1A", "CC", "EC", "2S"] = Field(
        ...,
        description="Coach class to check availability for.",
    )
    session_id: Optional[str] = None

    @field_validator("journey_date")
    @classmethod
    def journey_date_not_in_past(cls, v: date) -> date:
        from datetime import date as date_cls
        if v < date_cls.today():
            raise ValueError("journey_date cannot be in the past.")
        return v


class QuotaAvailability(BaseModel):
    """
    Availability under a single quota type.
    Nested inside AvailabilityResponse.
    """
    quota: Literal["GN", "TQ", "LD", "HP", "SS"] = Field(
        ...,
        description="GN=General, TQ=Tatkal, LD=Ladies, HP=Handicapped, SS=Senior Citizen",
    )
    available_seats: int = Field(..., ge=0)
    status: Literal["AVAILABLE", "RAC", "WL", "REGRET"] = Field(
        ...,
        description="AVAILABLE=seats open, RAC=reservation against cancellation, "
                    "WL=waitlist, REGRET=no booking possible.",
    )
    waitlist_number: Optional[int] = Field(
        default=None,
        description="Current waitlist position. Populated only when status is WL.",
        ge=1,
    )
    fare: Optional[float] = Field(
        default=None,
        description="Fare in INR for this class and quota.",
        ge=0,
    )


class AvailabilityResponse(BaseResponse):
    train_number: str
    train_name: str
    source: str
    destination: str
    journey_date: str
    class_type: str
    quotas: list[QuotaAvailability] = Field(
        ...,
        description="Availability broken down by quota type.",
    )
    natural_language_summary: str = Field(
        ...,
        examples=["12951 Rajdhani has 42 seats available in 3A under General quota on 15 Jan."],
    )


# ---------------------------------------------------------------------------
# /pnr-status
# ---------------------------------------------------------------------------

class PNRRequest(BaseModel):
    pnr_number: str = Field(
        ...,
        min_length=10,
        max_length=10,
        pattern=r"^\d{10}$",
        description="10-digit PNR number.",
        examples=["1234567890"],
    )
    session_id: Optional[str] = None


class PassengerStatus(BaseModel):
    """
    Booking status of a single passenger on the PNR.
    Nested inside PNRResponse.
    """
    passenger_index: int = Field(
        ...,
        ge=1,
        description="Passenger number (1-based).",
    )
    booking_status: str = Field(
        ...,
        description="Status at time of booking. E.g. 'WL/42'.",
        examples=["WL/42", "CNF", "RAC/12"],
    )
    current_status: str = Field(
        ...,
        description="Current live status. E.g. 'CNF/S5/32'.",
        examples=["CNF/S5/32", "RAC/12", "WL/3"],
    )
    coach: Optional[str] = Field(
        default=None,
        description="Assigned coach. Populated only if confirmed.",
        examples=["S5", "B2"],
    )
    berth: Optional[str] = Field(
        default=None,
        description="Assigned berth number and type. Populated only if confirmed.",
        examples=["32/LB", "14/UB"],
    )


class PNRResponse(BaseResponse):
    pnr_number: str
    train_number: str
    train_name: str
    journey_date: str
    source_station: str
    destination_station: str
    class_type: str
    chart_prepared: bool = Field(
        ...,
        description="Whether the reservation chart has been prepared for this train.",
    )
    passengers: list[PassengerStatus]
    natural_language_summary: str = Field(
        ...,
        examples=[
            "Your PNR 1234567890 for Rajdhani Express on 15 Jan is confirmed. "
            "Passenger 1 is in Coach S5, Berth 32 (Lower)."
        ],
    )


# ---------------------------------------------------------------------------
# Error
# ---------------------------------------------------------------------------

class ErrorResponse(BaseModel):
    success: bool = False
    message: str = Field(..., description="Human-readable error description.")
    error_code: Optional[str] = Field(
        default=None,
        description="Machine-readable error code for frontend handling.",
        examples=["TRAIN_NOT_FOUND", "INVALID_PNR", "API_TIMEOUT", "INTENT_UNCLEAR"],
    )
    detail: Optional[str] = Field(
        default=None,
        description="Additional debug detail. Omitted in production.",
    )